# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0b4d6f66a3e0165f06b8ff3135c2b77297a0937dd5f5fa3f80b975da82e6a36d9d10ae2e6b66d9f06460c11089fd9175e9a286cf77dbb1cd61c5e039d02a7cb

test:
  secret_key_base: b1ee3dc2447b712b5bd09f7e1c6b9da361cdea9a3c3e55f2e7077a75c443c7ef2e60213aba66a68c7fd1759e0c436b198f4f174a246230c3e20a07ccb38c9aaf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
